image: docker:git

stages:
  - deploy

before_script:
  - apk --update add bash python py-pip
  - pip install twine

services:
  - docker:stable-dind

release:
  stage: deploy
  when: manual
  script:
    - bin/release
