trigger:
  - master

pool:
  vmImage: 'ubuntu-latest'

variables:
- group: cassette

steps:
  - bash: |
      set -e
      pip install twine setuptools wheel
      python setup.py sdist bdist_wheel
      python -m twine check dist/*
      python -m twine upload dist/*
    displayName: "Publish package"
    env:
      TWINE_USERNAME: $(TWINE_USERNAME)
      TWINE_PASSWORD: $(TWINE_PASSWORD)
