trigger:
  - master

pool:
  vmImage: 'ubuntu-latest'

variables:
- group: cassette

steps:
  - bash: |
      set -e
      sudo apt-get install python3 python3-pip
      pip install twine setuptools wheel
      python setup.py sdist bdist_wheel
      twine check dist/*
      twine upload dist/*
    displayName: "Publish package"
    env:
      TWINE_USERNAME: $(TWINE_USERNAME)
      TWINE_PASSWORD: $(TWINE_PASSWORD)
